# dataset params
dataset: 'tiny'

# model params
encoder:
  arch: 'resnet18'
  feature_dim: 128
  cifar_small_image: False

decoder:
  image_shape: [3, 32, 32]
  n_channels: 128
  ch_mults: [1, 2, 2, 2]
  is_attn: [False, True, False, False]
  dropout: 0.1
  n_blocks: 2
  use_res_for_updown: False
  z_channels: 128

diffusion:
  betas: [1.0e-4, 0.02]
  # betas: 'inverted'
  n_T: 1000
  drop_prob: 0.1

# training params
batch_size: 64
lrate: 5.0e-5
lrate_ratio: 2
optim: 'AdamW'
optim_args:
  weight_decay: 0.05
  betas: [0.9, 0.95]
grad_clip_norm: 1

n_epoch: 800
warm_epoch: 20
load_epoch: -1
ema: 0.9999

n_sample: 30
save_dir: './output_tiny'
save_per: 100
